CREATE TABLE "WRS"."APP_DICTIONARY" 
   (	"DICT_CODE" NUMBER NOT NULL ENABLE, 
	"DICT_NAME" VARCHAR2(60), 
	"NOTE" VARCHAR2(4000), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("DICT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON TABLE "WRS"."APP_DICTIONARY"  IS '字典表';

CREATE TABLE "WRS"."APP_DICTIONARY_DATA" 
   (	"DICT_DATA_ID" NUMBER NOT NULL ENABLE, 
	"DICT_CODE" NUMBER, 
	"DICT_DATA_NAME" VARCHAR2(60), 
	"SHOW_INDEX" NUMBER, 
	"NOTE" VARCHAR2(4000), 
	"STATUS" CHAR(1), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("DICT_DATA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON TABLE "WRS"."APP_DICTIONARY_DATA"  IS '字典数据表';

CREATE TABLE "WRS"."APP_DOC" 
   (	"DOC_ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"DOC_CATALOG" VARCHAR2(20), 
	"DOC_TYPE" VARCHAR2(20), 
	"DOC_TITLE" VARCHAR2(60), 
	"DOC_NAME" VARCHAR2(60), 
	"DOC_URL" VARCHAR2(256), 
	"SUFFIX" VARCHAR2(60), 
	"FILE_PATH" VARCHAR2(256), 
	"FILE_SIZE" NUMBER, 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("DOC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_DOC"."DOC_ID" IS '文档ID'
 
   COMMENT ON COLUMN "WRS"."APP_DOC"."DOC_CATALOG" IS '文档目录'
 
   COMMENT ON COLUMN "WRS"."APP_DOC"."DOC_TYPE" IS '文档类型'
 
   COMMENT ON COLUMN "WRS"."APP_DOC"."DOC_TITLE" IS '文档标题'
 
   COMMENT ON COLUMN "WRS"."APP_DOC"."DOC_NAME" IS '文档名称'
 
   COMMENT ON COLUMN "WRS"."APP_DOC"."DOC_URL" IS '访问路径'
 
   COMMENT ON COLUMN "WRS"."APP_DOC"."SUFFIX" IS '文档名称后缀'
 
   COMMENT ON COLUMN "WRS"."APP_DOC"."FILE_PATH" IS '存储路径'
 
   COMMENT ON COLUMN "WRS"."APP_DOC"."FILE_SIZE" IS '文件大小'
 
   COMMENT ON COLUMN "WRS"."APP_DOC"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."APP_DOC"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."APP_DOC"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."APP_DOC"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."APP_DOC"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."APP_DOC"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."APP_DOC"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."APP_DOC"  IS '文档表';

CREATE TABLE "WRS"."APP_DOC_CATALOG" 
   (	"CATALOG_ID" NUMBER NOT NULL ENABLE, 
	"CATALOG_SUPERIOR_ID" NUMBER, 
	"CATALOG_NAME" VARCHAR2(60), 
	"SHOW_INDEX" NUMBER, 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("CATALOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON TABLE "WRS"."APP_DOC_CATALOG"  IS '文档目录表';

CREATE TABLE "WRS"."APP_DOC_TYPE" 
   (	"TYPE_ID" NUMBER NOT NULL ENABLE, 
	"TYPE_NAME" VARCHAR2(60), 
	"NOTE" VARCHAR2(4000), 
	"STATUS" CHAR(1), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON TABLE "WRS"."APP_DOC_TYPE"  IS '文档类型表';

CREATE TABLE "WRS"."APP_DUTY" 
   (	"DUTY_ID" VARCHAR2(50) DEFAULT SYS_GUID(), 
	"DUTY_NAME" VARCHAR2(60), 
	"BEGIN_TIME" DATE, 
	"END_TIME" DATE, 
	"DUTY_TYPE" CHAR(1) DEFAULT '1' NOT NULL ENABLE, 
	"NOTE" VARCHAR2(1000), 
	"CREATE_TIME" DATE, 
	"UPDATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1) DEFAULT 0 NOT NULL ENABLE, 
	 PRIMARY KEY ("DUTY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_DUTY"."DUTY_NAME" IS '排班名称'
 
   COMMENT ON COLUMN "WRS"."APP_DUTY"."BEGIN_TIME" IS '开始时间'
 
   COMMENT ON COLUMN "WRS"."APP_DUTY"."END_TIME" IS '结束时间'
 
   COMMENT ON COLUMN "WRS"."APP_DUTY"."DUTY_TYPE" IS '值班类型'
 
   COMMENT ON TABLE "WRS"."APP_DUTY"  IS '值班排班表';

CREATE TABLE "WRS"."APP_DUTY_DETAIL" 
   (	"DETAIL_ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"DUTY_ID" VARCHAR2(50) DEFAULT NULL, 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	"DUTY_DATE" DATE, 
	"PERSON_ID_JSON" VARCHAR2(1000), 
	"PERSON_NAME_JSON" VARCHAR2(1000), 
	"PERSON_NAMES" VARCHAR2(1000), 
	"NOTE" VARCHAR2(1000), 
	 PRIMARY KEY ("DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_DUTY_DETAIL"."DUTY_DATE" IS '值班日期'
 
   COMMENT ON COLUMN "WRS"."APP_DUTY_DETAIL"."PERSON_ID_JSON" IS '值班人员列-id json'
 
   COMMENT ON COLUMN "WRS"."APP_DUTY_DETAIL"."PERSON_NAME_JSON" IS '值班人员列-名称 json'
 
   COMMENT ON COLUMN "WRS"."APP_DUTY_DETAIL"."PERSON_NAMES" IS '所有值班人员名称(逗号分隔)'
 
   COMMENT ON COLUMN "WRS"."APP_DUTY_DETAIL"."NOTE" IS '备注'
 
   COMMENT ON TABLE "WRS"."APP_DUTY_DETAIL"  IS '值班排班明细表';

CREATE TABLE "WRS"."APP_DUTY_LOG" 
   (	"ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"DUTY_DETAIL_ID" VARCHAR2(50) DEFAULT NULL NOT NULL ENABLE, 
	"PROTECTION_RANK" NUMBER DEFAULT NULL, 
	"ACTUAL_DUTY" VARCHAR2(60) DEFAULT NULL, 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	"DUTY_LOG" VARCHAR2(1000), 
	"MATTERS" VARCHAR2(1000), 
	"NOTE" VARCHAR2(1000), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_DUTY_LOG"."PROTECTION_RANK" IS '防汛等级'
 
   COMMENT ON COLUMN "WRS"."APP_DUTY_LOG"."ACTUAL_DUTY" IS '实际值班人员'
 
   COMMENT ON COLUMN "WRS"."APP_DUTY_LOG"."CREATE_USER_CODE" IS '登记人员'
 
   COMMENT ON COLUMN "WRS"."APP_DUTY_LOG"."DUTY_LOG" IS '值班日志'
 
   COMMENT ON COLUMN "WRS"."APP_DUTY_LOG"."MATTERS" IS '待处理事项'
 
   COMMENT ON COLUMN "WRS"."APP_DUTY_LOG"."NOTE" IS '备注'
 
   COMMENT ON TABLE "WRS"."APP_DUTY_LOG"  IS '值班日志登记表';

CREATE TABLE "WRS"."APP_DUTY_PERSON" 
   (	"ID" VARCHAR2(50) DEFAULT SYS_GUID () NOT NULL ENABLE, 
	"PERSON_CODE" VARCHAR2(50), 
	"POSITION_ID" NUMBER, 
	"NAME" VARCHAR2(20), 
	"COMPANY_CODE" VARCHAR2(20), 
	"URL" VARCHAR2(1000), 
	"JOB_FUNCTION" VARCHAR2(1000), 
	"MOBILE_PHONE" VARCHAR2(20), 
	"OFFICE_PHONE" VARCHAR2(20), 
	"NOTE" VARCHAR2(1000), 
	"IS_DUTY" CHAR(1), 
	"IS_MSG_REC" CHAR(1), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	"IS_GROBAL_DUTY" CHAR(1), 
	"IS_WATER_DUTY" CHAR(1), 
	"BACKUP1" VARCHAR2(60), 
	"BACKUP2" VARCHAR2(60), 
	"BACKUP3" VARCHAR2(60), 
	"BACKUP4" VARCHAR2(60), 
	"BACKUP5" VARCHAR2(60), 
	"BACKUP6" VARCHAR2(60), 
	"BACKUP7" VARCHAR2(256), 
	"BACKUP8" VARCHAR2(256), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON TABLE "WRS"."APP_DUTY_PERSON"  IS '值班人员表';

CREATE TABLE "WRS"."APP_EMERGENCY" 
   (	"EMERGENCY_ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"TITLE" VARCHAR2(60), 
	"RESUME" VARCHAR2(256), 
	"PLAN_ID" VARCHAR2(50), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"STATUS" CHAR(1), 
	"END_CONDITION" CHAR(1), 
	"SUMMARY_CONTENT" VARCHAR2(4000), 
	"SUMMARY_TIME" DATE, 
	"NOTE" VARCHAR2(4000), 
	"BACKUP1" VARCHAR2(60), 
	"BACKUP2" VARCHAR2(60), 
	"BACKUP3" VARCHAR2(60), 
	"BACKUP4" VARCHAR2(60), 
	"BACKUP5" VARCHAR2(60), 
	"BACKUP6" VARCHAR2(60), 
	"BACKUP7" VARCHAR2(256), 
	"BACKUP8" VARCHAR2(256), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("EMERGENCY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."EMERGENCY_ID" IS '事件ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."TITLE" IS '标题'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."RESUME" IS '概要'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."PLAN_ID" IS '指导预案ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."START_TIME" IS '有效开始时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."END_TIME" IS '终止时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."STATUS" IS '状态 1-跟踪,2-结束,3-总结'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."END_CONDITION" IS '终止条件'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."SUMMARY_CONTENT" IS '总结内容'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."SUMMARY_TIME" IS '总结时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."BACKUP1" IS '备用字段1'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."BACKUP2" IS '备用字段2'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."BACKUP3" IS '备用字段3'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."BACKUP4" IS '备用字段4'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."BACKUP5" IS '备用字段5'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."BACKUP6" IS '备用字段6'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."BACKUP7" IS '备用字段7'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."BACKUP8" IS '备用字段8'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."APP_EMERGENCY"  IS '应急事件表';

CREATE TABLE "WRS"."APP_EMERGENCY_DOC" 
   (	"ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"FORI_ID" VARCHAR2(50), 
	"DOC_ID" VARCHAR2(50), 
	"DOC_NAME" VARCHAR2(60), 
	"DOC_URL" VARCHAR2(256), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_DOC"."ID" IS '自增ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_DOC"."FORI_ID" IS '外键ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_DOC"."DOC_ID" IS '文档ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_DOC"."DOC_NAME" IS '文档名称'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_DOC"."DOC_URL" IS '访问URL'
 
   COMMENT ON TABLE "WRS"."APP_EMERGENCY_DOC"  IS '应急事件附件表';

CREATE TABLE "WRS"."APP_EMERGENCY_PLAN" 
   (	"PLAN_ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"TITLE" VARCHAR2(60), 
	"RESUME" VARCHAR2(256), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"NOTE" VARCHAR2(4000), 
	"BACKUP1" VARCHAR2(60), 
	"BACKUP2" VARCHAR2(60), 
	"BACKUP3" VARCHAR2(60), 
	"BACKUP4" VARCHAR2(60), 
	"BACKUP5" VARCHAR2(60), 
	"BACKUP6" VARCHAR2(60), 
	"BACKUP7" VARCHAR2(256), 
	"BACKUP8" VARCHAR2(256), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("PLAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."PLAN_ID" IS '预案ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."TITLE" IS '标题'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."RESUME" IS '摘要'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."START_TIME" IS '有效开始时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."END_TIME" IS '有效结束时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."BACKUP1" IS '备用字段1'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."BACKUP2" IS '备用字段2'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."BACKUP3" IS '备用字段3'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."BACKUP4" IS '备用字段4'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."BACKUP5" IS '备用字段5'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."BACKUP6" IS '备用字段6'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."BACKUP7" IS '备用字段7'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."BACKUP8" IS '备用字段8'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."APP_EMERGENCY_PLAN"  IS '应急预案表';

CREATE TABLE "WRS"."APP_EMERGENCY_PLAN_DOC" 
   (	"ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"PLAN_ID" VARCHAR2(50), 
	"DOC_ID" VARCHAR2(50), 
	"DOC_NAME" VARCHAR2(60), 
	"DOC_URL" VARCHAR2(256), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN_DOC"."ID" IS '自增ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN_DOC"."PLAN_ID" IS '应急预案ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN_DOC"."DOC_ID" IS '文档ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN_DOC"."DOC_NAME" IS '文档名称'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PLAN_DOC"."DOC_URL" IS '访问URL'
 
   COMMENT ON TABLE "WRS"."APP_EMERGENCY_PLAN_DOC"  IS '应急预案附件表';

CREATE TABLE "WRS"."APP_EMERGENCY_PROCESS" 
   (	"PROCESS_ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"EMERGENCY_ID" VARCHAR2(50), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"EMERGENCY_DEPARTMENT" VARCHAR2(256), 
	"EMERGENCY_PERSON" VARCHAR2(256), 
	"PROCESS_CONTENT" VARCHAR2(4000), 
	"BACKUP1" VARCHAR2(60), 
	"BACKUP2" VARCHAR2(60), 
	"BACKUP3" VARCHAR2(60), 
	"BACKUP4" VARCHAR2(60), 
	"BACKUP5" VARCHAR2(60), 
	"BACKUP6" VARCHAR2(60), 
	"BACKUP7" VARCHAR2(256), 
	"BACKUP8" VARCHAR2(256), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("PROCESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."PROCESS_ID" IS '过程ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."EMERGENCY_ID" IS '事件ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."START_TIME" IS '开始时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."END_TIME" IS '结束时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."EMERGENCY_DEPARTMENT" IS '参与科室'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."EMERGENCY_PERSON" IS '应急人员'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."PROCESS_CONTENT" IS '过程内容'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."BACKUP1" IS '备用字段1'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."BACKUP2" IS '备用字段2'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."BACKUP3" IS '备用字段3'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."BACKUP4" IS '备用字段4'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."BACKUP5" IS '备用字段5'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."BACKUP6" IS '备用字段6'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."BACKUP7" IS '备用字段7'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."BACKUP8" IS '备用字段8'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."APP_EMERGENCY_PROCESS"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."APP_EMERGENCY_PROCESS"  IS '应急事件过程表';

CREATE TABLE "WRS"."APP_INTAKE_COST" 
   (	"COST_ID" VARCHAR2(50) DEFAULT SYS_GUID () NOT NULL ENABLE, 
	"MONTH" VARCHAR2(10), 
	"ORGAN_ID" VARCHAR2(50), 
	"INTAKE_USE" VARCHAR2(256), 
	"MONTH_INTAKE_QUANTITY" NUMBER, 
	"COST_FREQUENCY" CHAR(1), 
	"MONTH_COST" NUMBER, 
	"MONTH_PLAN_QUANTITY" NUMBER, 
	"EXCESS_RATIO" NUMBER, 
	"TOTAL_EXCESS_RATIO" NUMBER, 
	"INTAKE_ANALYSIS" VARCHAR2(256), 
	"NOTE" VARCHAR2(4000), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	"BACKUP1" VARCHAR2(60), 
	"BACKUP2" VARCHAR2(60), 
	"BACKUP3" VARCHAR2(60), 
	"BACKUP4" VARCHAR2(60), 
	"BACKUP5" VARCHAR2(60), 
	"BACKUP6" VARCHAR2(60), 
	"BACKUP7" VARCHAR2(256), 
	"BACKUP8" VARCHAR2(256), 
	 PRIMARY KEY ("COST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."COST_ID" IS '征费记录ID'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."MONTH" IS '年月'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."ORGAN_ID" IS '取水单位ID'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."INTAKE_USE" IS '取水用途'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."MONTH_INTAKE_QUANTITY" IS '月实际取水量'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."COST_FREQUENCY" IS '缴费频率：1-按月，2-按季，3-按年'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."MONTH_COST" IS '月缴费金额'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."MONTH_PLAN_QUANTITY" IS '月计划取水量'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."EXCESS_RATIO" IS '超计划取水比例'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."TOTAL_EXCESS_RATIO" IS '超累进收费比例'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."INTAKE_ANALYSIS" IS '取水分析说明'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."IS_DELETE" IS '是否已删除'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."BACKUP1" IS '备用字段1'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."BACKUP2" IS '备用字段2'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."BACKUP3" IS '备用字段3'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."BACKUP4" IS '备用字段4'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."BACKUP5" IS '备用字段5'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."BACKUP6" IS '备用字段6'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."BACKUP7" IS '备用字段7'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_COST"."BACKUP8" IS '备用字段8'
 
   COMMENT ON TABLE "WRS"."APP_INTAKE_COST"  IS '取水征费表';

CREATE TABLE "WRS"."APP_INTAKE_ORGAN" 
   (	"ORGAN_ID" VARCHAR2(50) DEFAULT SYS_GUID () NOT NULL ENABLE, 
	"ORGAN_CODE" VARCHAR2(60), 
	"ORGAN_NAME" VARCHAR2(60), 
	"REGION" VARCHAR2(60), 
	"CONTACT_PERSON" VARCHAR2(60), 
	"CONTACT_PHONE" VARCHAR2(60), 
	"ADDRESS" VARCHAR2(256), 
	"YEAR_INTAKE_QUANTITY" NUMBER, 
	"MAX_INTAKE_QUANTITY" NUMBER, 
	"NOTE" VARCHAR2(4000), 
	"BACKUP1" VARCHAR2(60), 
	"BACKUP2" VARCHAR2(60), 
	"BACKUP3" VARCHAR2(60), 
	"BACKUP4" VARCHAR2(60), 
	"BACKUP5" VARCHAR2(60), 
	"BACKUP6" VARCHAR2(60), 
	"BACKUP7" VARCHAR2(256), 
	"BACKUP8" VARCHAR2(256), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("ORGAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."ORGAN_ID" IS '取水单位ID'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."ORGAN_CODE" IS '取水单位编码'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."ORGAN_NAME" IS '取水单位名称'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."REGION" IS '行政区划名称'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."CONTACT_PERSON" IS '单位负责人'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."CONTACT_PHONE" IS '单位联系电话'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."ADDRESS" IS '单位地址'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."YEAR_INTAKE_QUANTITY" IS '批准年取水量'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."MAX_INTAKE_QUANTITY" IS '最大取水量'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."BACKUP1" IS '备用字段1'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."BACKUP2" IS '备用字段2'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."BACKUP3" IS '备用字段3'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."BACKUP4" IS '备用字段4'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."BACKUP5" IS '备用字段5'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."BACKUP6" IS '备用字段6'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."BACKUP7" IS '备用字段7'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."BACKUP8" IS '备用字段8'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."IS_DELETE" IS '是否已删除'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_ORGAN"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."APP_INTAKE_ORGAN"  IS '取水单位表';

CREATE TABLE "WRS"."APP_INTAKE_RECORD" 
   (	"RECORD_ID" VARCHAR2(50) DEFAULT SYS_GUID () NOT NULL ENABLE, 
	"MONTH" VARCHAR2(10), 
	"ORGAN_ID" VARCHAR2(50), 
	"ACTUAL_QUANTITY" NUMBER, 
	"PLAN_QUANTITY" NUMBER, 
	"BIASED_QUANTITY" NUMBER, 
	"LICENCE_QUANTITY" NUMBER, 
	"NOTE" VARCHAR2(4000), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	"BACKUP1" VARCHAR2(60), 
	"BACKUP2" VARCHAR2(60), 
	"BACKUP3" VARCHAR2(60), 
	"BACKUP4" VARCHAR2(60), 
	"BACKUP5" VARCHAR2(60), 
	"BACKUP6" VARCHAR2(60), 
	"BACKUP7" VARCHAR2(256), 
	"BACKUP8" VARCHAR2(256), 
	 PRIMARY KEY ("RECORD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."RECORD_ID" IS '取水记录ID'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."MONTH" IS '年月'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."ORGAN_ID" IS '取水单位ID'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."ACTUAL_QUANTITY" IS '实际取水量'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."PLAN_QUANTITY" IS '计划取水量'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."BIASED_QUANTITY" IS '取水偏差量'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."LICENCE_QUANTITY" IS '许可证取水量'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."IS_DELETE" IS '是否已删除'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."BACKUP1" IS '备用字段1'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."BACKUP2" IS '备用字段2'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."BACKUP3" IS '备用字段3'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."BACKUP4" IS '备用字段4'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."BACKUP5" IS '备用字段5'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."BACKUP6" IS '备用字段6'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."BACKUP7" IS '备用字段7'
 
   COMMENT ON COLUMN "WRS"."APP_INTAKE_RECORD"."BACKUP8" IS '备用字段8'
 
   COMMENT ON TABLE "WRS"."APP_INTAKE_RECORD"  IS '取水记录表';

CREATE TABLE "WRS"."APP_SMG_RECORD" 
   (	"RECORD_ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"BATCH_ID" VARCHAR2(50), 
	"CONTENT" VARCHAR2(1000), 
	"PERSON_CODE" VARCHAR2(256), 
	"STATUS" CHAR(1), 
	"NOTE" VARCHAR2(4000), 
	"BACKUP1" VARCHAR2(60), 
	"BACKUP2" VARCHAR2(60), 
	"BACKUP3" VARCHAR2(60), 
	"BACKUP4" VARCHAR2(60), 
	"BACKUP5" VARCHAR2(60), 
	"BACKUP6" VARCHAR2(60), 
	"BACKUP7" VARCHAR2(256), 
	"BACKUP8" VARCHAR2(256), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("RECORD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."RECORD_ID" IS '记录ID'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."BATCH_ID" IS '批次ID'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."CONTENT" IS '短信内容'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."PERSON_CODE" IS '短信接收人'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."STATUS" IS '状态'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."BACKUP1" IS '备用字段1'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."BACKUP2" IS '备用字段2'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."BACKUP3" IS '备用字段3'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."BACKUP4" IS '备用字段4'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."BACKUP5" IS '备用字段5'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."BACKUP6" IS '备用字段6'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."BACKUP7" IS '备用字段7'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."BACKUP8" IS '备用字段8'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."IS_DELETE" IS '是否已删除'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."APP_SMG_RECORD"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."APP_SMG_RECORD"  IS '短信发送记录表';

CREATE TABLE "WRS"."APP_WATER" 
   (	"BATCH_ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"BATCH_CODE" VARCHAR2(50), 
	"IMPORT_TIME" DATE, 
	"IMPORT_NAME" VARCHAR2(60), 
	"STATUS" CHAR(1), 
	"IS_SEND" CHAR(1), 
	"SEND_TIME" DATE, 
	"SEND_NAME" VARCHAR2(60), 
	"DOC_URL" VARCHAR2(256), 
	"NOTE" VARCHAR2(4000), 
	"BACKUP1" VARCHAR2(60), 
	"BACKUP2" VARCHAR2(60), 
	"BACKUP3" VARCHAR2(60), 
	"BACKUP4" VARCHAR2(60), 
	"BACKUP5" VARCHAR2(60), 
	"BACKUP6" VARCHAR2(60), 
	"BACKUP7" VARCHAR2(256), 
	"BACKUP8" VARCHAR2(256), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	"BATCH_TIME" DATE, 
	 PRIMARY KEY ("BATCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_WATER"."BATCH_ID" IS '批次ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."BATCH_CODE" IS '批次编号'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."IMPORT_TIME" IS '处理时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."IMPORT_NAME" IS '处理人'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."STATUS" IS '状态'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."IS_SEND" IS '是否已报送'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."SEND_TIME" IS '报送时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."SEND_NAME" IS '报送人'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."DOC_URL" IS '文档路径'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."BACKUP1" IS '备用字段1'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."BACKUP2" IS '备用字段2'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."BACKUP3" IS '备用字段3'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."BACKUP4" IS '备用字段4'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."BACKUP5" IS '备用字段5'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."BACKUP6" IS '备用字段6'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."BACKUP7" IS '备用字段7'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."BACKUP8" IS '备用字段8'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."IS_DELETE" IS '是否已删除'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."APP_WATER"  IS '水雨情表';

CREATE TABLE "WRS"."APP_WATER_RV" 
   (	"WATER_ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"BATCH_ID" VARCHAR2(50), 
	"DATA_SOURCE" VARCHAR2(60), 
	"STATION_NAME" VARCHAR2(60), 
	"RIVER_NAME" VARCHAR2(60), 
	"WATER_LEVEL" NUMBER, 
	"STORAGE_QUANTITY" NUMBER, 
	"IN_QUANTITY" NUMBER, 
	"OUT_QUANTITY" NUMBER, 
	"RAINFALL_QUANTITY" NUMBER, 
	"NOTE" VARCHAR2(4000), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("WATER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."WATER_ID" IS '水情ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."BATCH_ID" IS '批次ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."DATA_SOURCE" IS '来源'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."STATION_NAME" IS '站名'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."RIVER_NAME" IS '河名'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."WATER_LEVEL" IS '水位'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."STORAGE_QUANTITY" IS '蓄水量'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."IN_QUANTITY" IS '入库流量'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."OUT_QUANTITY" IS '出库流量'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."RAINFALL_QUANTITY" IS '日雨量'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."IS_DELETE" IS '是否已删除'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."APP_WATER_RV"  IS '水库水情表';

CREATE TABLE "WRS"."APP_WATER_RV_DETAIL" 
   (	"DETAIL_ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"WATER_ID" VARCHAR2(50), 
	"BATCH_ID" VARCHAR2(50), 
	"DATES" VARCHAR2(60), 
	"TIMES" VARCHAR2(60), 
	"UPSTREAM_LEVER" NUMBER, 
	"CAPACITY" NUMBER, 
	"IN_QUANTITY" NUMBER, 
	"OUT_QUANTITY" NUMBER, 
	"NOTE" VARCHAR2(4000), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."DETAIL_ID" IS '明细ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."WATER_ID" IS '水情ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."BATCH_ID" IS '批次ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."DATES" IS '日期'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."TIMES" IS '时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."UPSTREAM_LEVER" IS '上游水位'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."CAPACITY" IS '水库库容'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."IN_QUANTITY" IS '入库流量'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."OUT_QUANTITY" IS '出库流量'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."IS_DELETE" IS '是否已删除'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_RV_DETAIL"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."APP_WATER_RV_DETAIL"  IS '水库水情明细表';

CREATE TABLE "WRS"."APP_WATER_ST" 
   (	"WATER_ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"BATCH_ID" VARCHAR2(50), 
	"DATA_SOURCE" VARCHAR2(60), 
	"STATION_NAME" VARCHAR2(60), 
	"RIVER_NAME" VARCHAR2(60), 
	"WATER_LEVEL" NUMBER, 
	"QUANTITY" NUMBER, 
	"TREND" VARCHAR2(60), 
	"DAILY_AVG_QUANTITY" NUMBER, 
	"WARNING_LEVEL" NUMBER, 
	"NOTE" VARCHAR2(4000), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("WATER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."WATER_ID" IS '水情ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."BATCH_ID" IS '批次ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."DATA_SOURCE" IS '来源'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."STATION_NAME" IS '站名'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."RIVER_NAME" IS '河名'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."WATER_LEVEL" IS '水位'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."QUANTITY" IS '流量'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."TREND" IS '涨势'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."DAILY_AVG_QUANTITY" IS '日均流量'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."WARNING_LEVEL" IS '警戒水位'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."APP_WATER_ST"  IS '站点水情表';

CREATE TABLE "WRS"."APP_WATER_ST_DETAIL" 
   (	"DETAIL_ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"WATER_ID" VARCHAR2(50), 
	"BATCH_ID" VARCHAR2(50), 
	"DATES" VARCHAR2(60), 
	"TIMES" VARCHAR2(60), 
	"UPSTREAM_LEVER" NUMBER, 
	"DOWNSTREAM_LEVER" NUMBER, 
	"DISCHARGE_QUANTITY" NUMBER, 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."APP_WATER_ST_DETAIL"."DETAIL_ID" IS '明细ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST_DETAIL"."WATER_ID" IS '水情ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST_DETAIL"."BATCH_ID" IS '批次ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST_DETAIL"."DATES" IS '日期'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST_DETAIL"."TIMES" IS '时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST_DETAIL"."UPSTREAM_LEVER" IS '上游水位'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST_DETAIL"."DOWNSTREAM_LEVER" IS '下游水位'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST_DETAIL"."DISCHARGE_QUANTITY" IS '下泄流量'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST_DETAIL"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST_DETAIL"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST_DETAIL"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST_DETAIL"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST_DETAIL"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST_DETAIL"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."APP_WATER_ST_DETAIL"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."APP_WATER_ST_DETAIL"  IS '站点水情明细表';

CREATE TABLE "WRS"."SYS_DEPARTMENT" 
   (	"DEPARTMENT_ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"DEPARTMENT_SUPERIOR_ID" VARCHAR2(50), 
	"DEPARTMENT_NAME" VARCHAR2(60), 
	"STATUS" CHAR(1) DEFAULT 1, 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("DEPARTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."SYS_DEPARTMENT"."DEPARTMENT_ID" IS '部门ID'
 
   COMMENT ON COLUMN "WRS"."SYS_DEPARTMENT"."DEPARTMENT_SUPERIOR_ID" IS '上级部门ID'
 
   COMMENT ON COLUMN "WRS"."SYS_DEPARTMENT"."DEPARTMENT_NAME" IS '部门名称'
 
   COMMENT ON COLUMN "WRS"."SYS_DEPARTMENT"."STATUS" IS '部门状态：1-已启用，2-待启用，3-已禁用'
 
   COMMENT ON COLUMN "WRS"."SYS_DEPARTMENT"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."SYS_DEPARTMENT"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."SYS_DEPARTMENT"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."SYS_DEPARTMENT"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."SYS_DEPARTMENT"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."SYS_DEPARTMENT"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."SYS_DEPARTMENT"  IS '部门表';

CREATE TABLE "WRS"."SYS_DEPARTMENT_USER" 
   (	"USER_CODE" VARCHAR2(20), 
	"DEPARTMENT_ID" VARCHAR2(50), 
	 CONSTRAINT "SYS_DEPARTMENT_USER_PK" UNIQUE ("USER_CODE", "DEPARTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."SYS_DEPARTMENT_USER"."USER_CODE" IS '用户ID'
 
   COMMENT ON COLUMN "WRS"."SYS_DEPARTMENT_USER"."DEPARTMENT_ID" IS '部门ID'
 
   COMMENT ON TABLE "WRS"."SYS_DEPARTMENT_USER"  IS '部门用户关系表';

CREATE TABLE "WRS"."SYS_MENU" 
   (	"MENU_ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"MENU_NAME" VARCHAR2(60), 
	"MENU_SUPERIOR_ID" VARCHAR2(50), 
	"MENU_URL" VARCHAR2(256), 
	"MENU_PARAM" VARCHAR2(256), 
	"MENU_TYPE" CHAR(1), 
	"MENU_OPEN_TYPE" CHAR(1), 
	"MENU_SHOW_INDEX" NUMBER, 
	"MENU_ICON_CLASS" VARCHAR2(256), 
	"STATUS" CHAR(1), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."SYS_MENU"."MENU_ID" IS '菜单ID'
 
   COMMENT ON COLUMN "WRS"."SYS_MENU"."MENU_NAME" IS '菜单名称'
 
   COMMENT ON COLUMN "WRS"."SYS_MENU"."MENU_SUPERIOR_ID" IS '父级菜单ID'
 
   COMMENT ON COLUMN "WRS"."SYS_MENU"."MENU_URL" IS '菜单链接'
 
   COMMENT ON COLUMN "WRS"."SYS_MENU"."MENU_PARAM" IS '菜单参数'
 
   COMMENT ON COLUMN "WRS"."SYS_MENU"."MENU_TYPE" IS '菜单类型'
 
   COMMENT ON COLUMN "WRS"."SYS_MENU"."MENU_OPEN_TYPE" IS '权限菜单'
 
   COMMENT ON COLUMN "WRS"."SYS_MENU"."MENU_SHOW_INDEX" IS '排序序号'
 
   COMMENT ON COLUMN "WRS"."SYS_MENU"."MENU_ICON_CLASS" IS '菜单样式'
 
   COMMENT ON COLUMN "WRS"."SYS_MENU"."STATUS" IS '菜单状态：1-已启用，2-待启用，3-已禁用'
 
   COMMENT ON COLUMN "WRS"."SYS_MENU"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."SYS_MENU"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."SYS_MENU"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."SYS_MENU"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."SYS_MENU"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."SYS_MENU"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."SYS_MENU"  IS '菜单表';

CREATE TABLE "WRS"."SYS_ROLE" 
   (	"ROLE_ID" VARCHAR2(50) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"ROLE_NAME" VARCHAR2(60), 
	"NOTE" VARCHAR2(4000), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."SYS_ROLE"."ROLE_ID" IS '角色ID'
 
   COMMENT ON COLUMN "WRS"."SYS_ROLE"."ROLE_NAME" IS '角色名称'
 
   COMMENT ON COLUMN "WRS"."SYS_ROLE"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."SYS_ROLE"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."SYS_ROLE"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."SYS_ROLE"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."SYS_ROLE"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."SYS_ROLE"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."SYS_ROLE"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."SYS_ROLE"  IS '角色表';

CREATE TABLE "WRS"."SYS_ROLE_MENU" 
   (	"ROLE_ID" VARCHAR2(50), 
	"MENU_ID" VARCHAR2(50), 
	 PRIMARY KEY ("ROLE_ID", "MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."SYS_ROLE_MENU"."ROLE_ID" IS '角色ID'
 
   COMMENT ON COLUMN "WRS"."SYS_ROLE_MENU"."MENU_ID" IS '菜单ID'
 
   COMMENT ON TABLE "WRS"."SYS_ROLE_MENU"  IS '角色菜单关系表';

CREATE TABLE "WRS"."SYS_USER" 
   (	"USER_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(60), 
	"USER_PASSWORD" VARCHAR2(60), 
	"NOTE" VARCHAR2(4000), 
	"DEFAULT_ROLE" VARCHAR2(60), 
	"STATUS" CHAR(1), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("USER_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."SYS_USER"."USER_CODE" IS '用户编号'
 
   COMMENT ON COLUMN "WRS"."SYS_USER"."USER_NAME" IS '用户名称'
 
   COMMENT ON COLUMN "WRS"."SYS_USER"."USER_PASSWORD" IS '用户密码'
 
   COMMENT ON COLUMN "WRS"."SYS_USER"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."SYS_USER"."DEFAULT_ROLE" IS '默认角色'
 
   COMMENT ON COLUMN "WRS"."SYS_USER"."STATUS" IS '用户状态'
 
   COMMENT ON COLUMN "WRS"."SYS_USER"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."SYS_USER"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."SYS_USER"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."SYS_USER"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."SYS_USER"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."SYS_USER"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."SYS_USER"  IS '用户表';

CREATE TABLE "WRS"."SYS_USER_LOG" 
   (	"LOG_ID" VARCHAR2(50) DEFAULT SYS_GUID(), 
	"USER_CODE" VARCHAR2(20), 
	"REQ_URL" VARCHAR2(256), 
	"ACTION_TYPE" VARCHAR2(256), 
	"ACTION_MODULE" VARCHAR2(20), 
	"ACTION_TIME" DATE, 
	"NOTE" VARCHAR2(4000), 
	 PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."SYS_USER_LOG"."LOG_ID" IS '日志ID'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_LOG"."USER_CODE" IS '用户编号'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_LOG"."REQ_URL" IS '请求地址'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_LOG"."ACTION_TYPE" IS '操作类型'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_LOG"."ACTION_MODULE" IS '操作模块'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_LOG"."ACTION_TIME" IS '操作时间'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_LOG"."NOTE" IS '备注'
 
   COMMENT ON TABLE "WRS"."SYS_USER_LOG"  IS '用户操作日志表';

CREATE TABLE "WRS"."SYS_USER_MENU" 
   (	"USE_ID" NUMBER, 
	"USER_CODE" VARCHAR2(20), 
	"MENU_ID" NUMBER, 
	"LASTEST_OPEN_TIME" DATE, 
	"OPEN_NUMBER" NUMBER, 
	 PRIMARY KEY ("USE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "WRS" 
 

   COMMENT ON TABLE "WRS"."SYS_USER_MENU"  IS '用户对菜单使用情况表';

CREATE TABLE "WRS"."SYS_USER_ROLE" 
   (	"USER_CODE" VARCHAR2(20), 
	"ROLE_ID" VARCHAR2(50), 
	 PRIMARY KEY ("USER_CODE", "ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."SYS_USER_ROLE"."USER_CODE" IS '用户编号'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_ROLE"."ROLE_ID" IS '角色ID'
 
   COMMENT ON TABLE "WRS"."SYS_USER_ROLE"  IS '用户角色关系表';

CREATE TABLE "WRS"."SYS_USER_TEST" 
   (	"USER_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(60), 
	"USER_PASSWORD" VARCHAR2(60), 
	"NOTE" VARCHAR2(4000), 
	"DEFAULT_ROLE" VARCHAR2(60), 
	"STATUS" CHAR(1), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("USER_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."SYS_USER_TEST"."USER_CODE" IS '用户编号'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_TEST"."USER_NAME" IS '用户名称'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_TEST"."USER_PASSWORD" IS '用户密码'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_TEST"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_TEST"."DEFAULT_ROLE" IS '默认角色'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_TEST"."STATUS" IS '用户状态'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_TEST"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_TEST"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_TEST"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_TEST"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_TEST"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."SYS_USER_TEST"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."SYS_USER_TEST"  IS '用户表';

CREATE TABLE "WRS"."WCPS_PATROL" 
   (	"PATROL_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"PATROL_TITLE" VARCHAR2(60), 
	"PATROL_TYPE" CHAR(1), 
	"DEPARTMENT_NAME" VARCHAR2(60), 
	"PATROL_PERSON" VARCHAR2(256), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"STATUS" CHAR(1), 
	"NOTE" VARCHAR2(4000), 
	"BACKUP1" VARCHAR2(60), 
	"BACKUP2" VARCHAR2(60), 
	"BACKUP3" VARCHAR2(60), 
	"BACKUP4" VARCHAR2(60), 
	"BACKUP5" VARCHAR2(60), 
	"BACKUP6" VARCHAR2(60), 
	"BACKUP7" VARCHAR2(256), 
	"BACKUP8" VARCHAR2(256), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("PATROL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."PATROL_ID" IS '巡查ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."PATROL_TITLE" IS '巡查标题'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."PATROL_TYPE" IS '巡查类型：1-河道综合巡查、2-河长制工作巡查、3-取水许可和水资源费征收管理巡查、4-水量调度巡查、5-专项巡查'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."DEPARTMENT_NAME" IS '巡查部门'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."PATROL_PERSON" IS '巡查员'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."START_TIME" IS '开始时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."END_TIME" IS '结束时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."STATUS" IS '状态'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."BACKUP1" IS '备用字段1'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."BACKUP2" IS '备用字段2'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."BACKUP3" IS '备用字段3'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."BACKUP4" IS '备用字段4'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."BACKUP5" IS '备用字段5'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."BACKUP6" IS '备用字段6'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."BACKUP7" IS '备用字段7'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."BACKUP8" IS '备用字段8'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."WCPS_PATROL"  IS '流域巡查记录表';

CREATE TABLE "WRS"."WCPS_PATROL_DETAIL" 
   (	"DETAIL_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"PATROL_ID" VARCHAR2(50), 
	"PROBLEM" VARCHAR2(256), 
	"PROPOSE" VARCHAR2(256), 
	"RESULT" VARCHAR2(256), 
	"PROCESS" VARCHAR2(256), 
	"NOTE" VARCHAR2(4000), 
	"BACKUP1" VARCHAR2(60), 
	"BACKUP2" VARCHAR2(60), 
	"BACKUP3" VARCHAR2(60), 
	"BACKUP4" VARCHAR2(60), 
	"BACKUP5" VARCHAR2(60), 
	"BACKUP6" VARCHAR2(60), 
	"BACKUP7" VARCHAR2(256), 
	"BACKUP8" VARCHAR2(256), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."DETAIL_ID" IS '问题跟踪ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."PATROL_ID" IS '巡查ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."PROBLEM" IS '巡查ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."PROPOSE" IS '处理意见'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."RESULT" IS '处理结果'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."PROCESS" IS '处理过程'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."BACKUP1" IS '备用字段1'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."BACKUP2" IS '备用字段2'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."BACKUP3" IS '备用字段3'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."BACKUP4" IS '备用字段4'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."BACKUP5" IS '备用字段5'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."BACKUP6" IS '备用字段6'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."BACKUP7" IS '备用字段7'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."BACKUP8" IS '备用字段8'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DETAIL"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."WCPS_PATROL_DETAIL"  IS '流域巡查问题跟踪表';

CREATE TABLE "WRS"."WCPS_PATROL_DOC" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PATROL_ID" NUMBER, 
	"DOC_ID" NUMBER, 
	"DOC_TITLE" VARCHAR2(60), 
	"DOC_NAME" VARCHAR2(60), 
	"DOC_URL" VARCHAR2(256), 
	"SUFFIX" VARCHAR2(60), 
	"FILE_PATH" VARCHAR2(256), 
	"FILE_SIZE" NUMBER, 
	"BACKUP1" VARCHAR2(60), 
	"BACKUP2" VARCHAR2(60), 
	"BACKUP3" VARCHAR2(60), 
	"BACKUP4" VARCHAR2(60), 
	"BACKUP5" VARCHAR2(60), 
	"BACKUP6" VARCHAR2(60), 
	"BACKUP7" VARCHAR2(256), 
	"BACKUP8" VARCHAR2(256), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."ID" IS '自增ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."PATROL_ID" IS '巡查ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."DOC_ID" IS '文档ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."DOC_TITLE" IS '文档标题'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."DOC_NAME" IS '文档名称'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."DOC_URL" IS '访问URL'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."SUFFIX" IS '文档名称后缀'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."FILE_PATH" IS '存储路径'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."FILE_SIZE" IS '文件大小'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."BACKUP1" IS '备用字段1'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."BACKUP2" IS '备用字段2'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."BACKUP3" IS '备用字段3'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."BACKUP4" IS '备用字段4'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."BACKUP5" IS '备用字段5'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."BACKUP6" IS '备用字段6'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."BACKUP7" IS '备用字段7'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."BACKUP8" IS '备用字段8'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_DOC"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."WCPS_PATROL_DOC"  IS '流域巡查附件表';

CREATE TABLE "WRS"."WCPS_PATROL_ITEM" 
   (	"ITEM_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"PATROL_ID" VARCHAR2(50), 
	"ITEM_TITLE" VARCHAR2(256), 
	"ITEM_RESULT" VARCHAR2(256), 
	"ITEM_PROBLEM" VARCHAR2(256), 
	"NOTE" VARCHAR2(4000), 
	"BACKUP1" VARCHAR2(60), 
	"BACKUP2" VARCHAR2(60), 
	"BACKUP3" VARCHAR2(60), 
	"BACKUP4" VARCHAR2(60), 
	"BACKUP5" VARCHAR2(60), 
	"BACKUP6" VARCHAR2(60), 
	"BACKUP7" VARCHAR2(256), 
	"BACKUP8" VARCHAR2(256), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."ITEM_ID" IS '事项ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."PATROL_ID" IS '巡查ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."ITEM_TITLE" IS '巡查事项'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."ITEM_RESULT" IS '巡查结果'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."ITEM_PROBLEM" IS '发现问题处理结果'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."BACKUP1" IS '备用字段1'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."BACKUP2" IS '备用字段2'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."BACKUP3" IS '备用字段3'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."BACKUP4" IS '备用字段4'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."BACKUP5" IS '备用字段5'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."BACKUP6" IS '备用字段6'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."BACKUP7" IS '备用字段7'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."BACKUP8" IS '备用字段8'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_ITEM"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."WCPS_PATROL_ITEM"  IS '流域巡查记录事项表';

CREATE TABLE "WRS"."WCPS_PATROL_PLAN" 
   (	"PLAN_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"PATROL_TIME" NUMBER, 
	"PATROL_AREA" VARCHAR2(60), 
	"PATROL_TYPE" CHAR(1), 
	"PATROL_NUMBER" CHAR(5), 
	"DEPARTMENT_NAME" VARCHAR2(60), 
	"CREATE_USER_NAME" VARCHAR2(20), 
	"UPDATE_USER_NAME" VARCHAR2(20), 
	"NOTE" VARCHAR2(4000), 
	"BACKUP1" VARCHAR2(60), 
	"BACKUP2" VARCHAR2(60), 
	"BACKUP3" VARCHAR2(60), 
	"BACKUP4" VARCHAR2(60), 
	"BACKUP5" VARCHAR2(60), 
	"BACKUP6" VARCHAR2(60), 
	"BACKUP7" VARCHAR2(256), 
	"BACKUP8" VARCHAR2(256), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("PLAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."PLAN_ID" IS '巡查计划ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."PATROL_TIME" IS '巡查年份'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."PATROL_AREA" IS '巡查地市'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."PATROL_TYPE" IS '巡查类型'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."PATROL_NUMBER" IS '巡查次数'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."DEPARTMENT_NAME" IS '巡查部门'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."CREATE_USER_NAME" IS '编制人姓名'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."UPDATE_USER_NAME" IS '修改人姓名'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."BACKUP1" IS '备用字段1'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."BACKUP2" IS '备用字段2'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."BACKUP3" IS '备用字段3'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."BACKUP4" IS '备用字段4'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."BACKUP5" IS '备用字段5'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."BACKUP6" IS '备用字段6'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."BACKUP7" IS '备用字段7'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."BACKUP8" IS '备用字段8'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."WCPS_PATROL_PLAN"  IS '流域巡查计划表';

CREATE TABLE "WRS"."WCPS_PATROL_PLAN_DOC" 
   (	"ID" VARCHAR2(50) NOT NULL ENABLE, 
	"PLAN_ID" VARCHAR2(50), 
	"DOC_ID" VARCHAR2(50), 
	"DOC_TITLE" VARCHAR2(60), 
	"DOC_NAME" VARCHAR2(60), 
	"DOC_URL" VARCHAR2(256), 
	"SUFFIX" VARCHAR2(60), 
	"FILE_PATH" VARCHAR2(256), 
	"FILE_SIZE" NUMBER, 
	"BACKUP1" VARCHAR2(60), 
	"BACKUP2" VARCHAR2(60), 
	"BACKUP3" VARCHAR2(60), 
	"BACKUP4" VARCHAR2(60), 
	"BACKUP5" VARCHAR2(60), 
	"BACKUP6" VARCHAR2(60), 
	"BACKUP7" VARCHAR2(256), 
	"BACKUP8" VARCHAR2(256), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."ID" IS '自增ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."PLAN_ID" IS '巡查计划ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."DOC_ID" IS '文档ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."DOC_TITLE" IS '文档标题'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."DOC_NAME" IS '文档名称'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."DOC_URL" IS '访问URL'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."SUFFIX" IS '文档名称后缀'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."FILE_PATH" IS '存储路径'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."FILE_SIZE" IS '文件大小'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."BACKUP1" IS '备用字段1'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."BACKUP2" IS '备用字段2'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."BACKUP3" IS '备用字段3'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."BACKUP4" IS '备用字段4'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."BACKUP5" IS '备用字段5'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."BACKUP6" IS '备用字段6'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."BACKUP7" IS '备用字段7'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."BACKUP8" IS '备用字段8'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."WCPS_PATROL_PLAN_DOC"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."WCPS_PATROL_PLAN_DOC"  IS '流域巡查计划附件表';

CREATE TABLE "WRS"."WRS_AVG_WATER_CONFIG" 
   (	"CONFIG_ID" NUMBER NOT NULL ENABLE, 
	"CONFIG_TYPE" CHAR(1), 
	"PROJECT_ID" NUMBER, 
	"MONTH" NUMBER, 
	"RESERVOIR_1" NUMBER, 
	"RESERVOIR_2" NUMBER, 
	"RESERVOIR_3" NUMBER, 
	"RESERVOIR_4" NUMBER, 
	"RESERVOIR_5" NUMBER, 
	"TRANSECT_1" NUMBER, 
	"TRANSECT_2" NUMBER, 
	"TRANSECT_3" NUMBER, 
	"TRANSECT_4" NUMBER, 
	"TRANSECT_5" NUMBER, 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("CONFIG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."CONFIG_ID" IS '配置ID'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."CONFIG_TYPE" IS '配置类型：0-基础数据，1-方案数据'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."PROJECT_ID" IS '方案ID'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."MONTH" IS '月份'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."RESERVOIR_1" IS '枫树坝入库水位'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."RESERVOIR_2" IS '新丰江入库水位'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."RESERVOIR_3" IS '白盆珠入库水位'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."RESERVOIR_4" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."RESERVOIR_5" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."TRANSECT_1" IS '枫新河区间水位'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."TRANSECT_2" IS '河岭区间水位'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."TRANSECT_3" IS '白岭区间水位'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."TRANSECT_4" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."TRANSECT_5" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."WRS_AVG_WATER_CONFIG"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."WRS_AVG_WATER_CONFIG"  IS '月均来水配置表';

CREATE TABLE "WRS"."WRS_PROJECT" 
   (	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_CODE" NUMBER, 
	"PROJECT_TITLE" VARCHAR2(60), 
	"PROJECT_TYPE" CHAR(1), 
	"STATUS" CHAR(1), 
	"NOTE" VARCHAR2(4000), 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("PROJECT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."WRS_PROJECT"."PROJECT_ID" IS '方案ID'
 
   COMMENT ON COLUMN "WRS"."WRS_PROJECT"."PROJECT_CODE" IS '方案编号'
 
   COMMENT ON COLUMN "WRS"."WRS_PROJECT"."PROJECT_TITLE" IS '方案标题'
 
   COMMENT ON COLUMN "WRS"."WRS_PROJECT"."PROJECT_TYPE" IS '类型：1-枯水期，2-汛期'
 
   COMMENT ON COLUMN "WRS"."WRS_PROJECT"."STATUS" IS '状态：0-草稿，1-正式'
 
   COMMENT ON COLUMN "WRS"."WRS_PROJECT"."NOTE" IS '备注'
 
   COMMENT ON COLUMN "WRS"."WRS_PROJECT"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."WRS_PROJECT"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."WRS_PROJECT"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."WRS_PROJECT"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."WRS_PROJECT"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."WRS_PROJECT"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."WRS_PROJECT"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."WRS_PROJECT"  IS '水量调度方案表';

CREATE TABLE "WRS"."WRS_RESERVOIR_CONFIG" 
   (	"CONFIG_ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER, 
	"YEAR" NUMBER, 
	"MONTH" NUMBER, 
	"START_RESERVOIR_1" NUMBER, 
	"START_RESERVOIR_2" NUMBER, 
	"START_RESERVOIR_3" NUMBER, 
	"START_RESERVOIR_4" NUMBER, 
	"START_RESERVOIR_5" NUMBER, 
	"CTRL_RESERVOIR_1" NUMBER, 
	"CTRL_RESERVOIR_2" NUMBER, 
	"CTRL_RESERVOIR_3" NUMBER, 
	"CTRL_RESERVOIR_4" NUMBER, 
	"CTRL_RESERVOIR_5" NUMBER, 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("CONFIG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."CONFIG_ID" IS '配置ID'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."PROJECT_ID" IS '方案ID'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."YEAR" IS '年份'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."MONTH" IS '月份'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."START_RESERVOIR_1" IS '枫树坝水位'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."START_RESERVOIR_2" IS '新丰江水位'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."START_RESERVOIR_3" IS '白盆珠水位'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."START_RESERVOIR_4" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."START_RESERVOIR_5" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."CTRL_RESERVOIR_1" IS '枫树坝水位'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."CTRL_RESERVOIR_2" IS '新丰江水位'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."CTRL_RESERVOIR_3" IS '白盆珠水位'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."CTRL_RESERVOIR_4" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."CTRL_RESERVOIR_5" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_CONFIG"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."WRS_RESERVOIR_CONFIG"  IS '水库水位配置表';

CREATE TABLE "WRS"."WRS_RESERVOIR_RESULT" 
   (	"RESULT_ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER, 
	"MONTH" NUMBER, 
	"IN_QUANTITY_1" NUMBER, 
	"OUT_QUANTITY_1" NUMBER, 
	"WATER_VAR_1" NUMBER, 
	"MONTH_LEVEL_1" NUMBER, 
	"MONTH_WATER_1" NUMBER, 
	"IN_QUANTITY_2" NUMBER, 
	"OUT_QUANTITY_2" NUMBER, 
	"WATER_VAR_2" NUMBER, 
	"MONTH_LEVEL_2" NUMBER, 
	"MONTH_WATER_2" NUMBER, 
	"IN_QUANTITY_3" NUMBER, 
	"OUT_QUANTITY_3" NUMBER, 
	"WATER_VAR_3" NUMBER, 
	"MONTH_LEVEL_3" NUMBER, 
	"MONTH_WATER_3" NUMBER, 
	"IN_QUANTITY_4" NUMBER, 
	"OUT_QUANTITY_4" NUMBER, 
	"WATER_VAR_4" NUMBER, 
	"MONTH_LEVEL_4" NUMBER, 
	"MONTH_WATER_4" NUMBER, 
	"IN_QUANTITY_5" NUMBER, 
	"OUT_QUANTITY_5" NUMBER, 
	"WATER_VAR_5" NUMBER, 
	"MONTH_LEVEL_5" NUMBER, 
	"MONTH_WATER_5" NUMBER, 
	"IN_QUANTITY" NUMBER, 
	"OUT_QUANTITY" NUMBER, 
	"WATER_VAR" NUMBER, 
	"MONTH_LEVEL" NUMBER, 
	"MONTH_WATER" NUMBER, 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("RESULT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."RESULT_ID" IS '预测成果ID'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."PROJECT_ID" IS '方案ID'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."MONTH" IS '月份'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."IN_QUANTITY_1" IS '新丰江预测入库'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."OUT_QUANTITY_1" IS '新丰江控制出库'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."WATER_VAR_1" IS '新丰江蓄水变量'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."MONTH_LEVEL_1" IS '新丰江月末水位'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."MONTH_WATER_1" IS '新丰江月末蓄水量'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."IN_QUANTITY_2" IS '枫树坝预测入库'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."OUT_QUANTITY_2" IS '枫树坝控制出库'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."WATER_VAR_2" IS '枫树坝蓄水变量'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."MONTH_LEVEL_2" IS '枫树坝月末水位'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."MONTH_WATER_2" IS '枫树坝月末蓄水量'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."IN_QUANTITY_3" IS '白盆珠预测入库'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."OUT_QUANTITY_3" IS '白盆珠控制出库'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."WATER_VAR_3" IS '白盆珠蓄水变量'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."MONTH_LEVEL_3" IS '白盆珠月末水位'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."MONTH_WATER_3" IS '白盆珠月末蓄水量'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."IN_QUANTITY_4" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."OUT_QUANTITY_4" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."WATER_VAR_4" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."MONTH_LEVEL_4" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."MONTH_WATER_4" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."IN_QUANTITY_5" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."OUT_QUANTITY_5" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."WATER_VAR_5" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."MONTH_LEVEL_5" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."MONTH_WATER_5" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."IN_QUANTITY" IS '合计预测入库'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."OUT_QUANTITY" IS '合计控制出库'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."WATER_VAR" IS '合计蓄水变量'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."MONTH_LEVEL" IS '合计月末水位'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."MONTH_WATER" IS '合计月末蓄水量'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."WRS_RESERVOIR_RESULT"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."WRS_RESERVOIR_RESULT"  IS '水库预测成果表';

CREATE TABLE "WRS"."WRS_TRANSECT_RESULT" 
   (	"RESULT_ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER, 
	"MONTH" NUMBER, 
	"TRANSECT_1" NUMBER, 
	"TRANSECT_2" NUMBER, 
	"TRANSECT_3" NUMBER, 
	"TRANSECT_4" NUMBER, 
	"TRANSECT_5" NUMBER, 
	"CREATE_TIME" DATE, 
	"CREATE_USER_CODE" VARCHAR2(20), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_CODE" VARCHAR2(20), 
	"IS_DELETE" CHAR(1), 
	"DELETE_TIME" DATE, 
	"DELETE_USER_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("RESULT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "WRS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "WRS" 
 

   COMMENT ON COLUMN "WRS"."WRS_TRANSECT_RESULT"."RESULT_ID" IS '预测成果ID'
 
   COMMENT ON COLUMN "WRS"."WRS_TRANSECT_RESULT"."PROJECT_ID" IS '方案ID'
 
   COMMENT ON COLUMN "WRS"."WRS_TRANSECT_RESULT"."MONTH" IS '月份'
 
   COMMENT ON COLUMN "WRS"."WRS_TRANSECT_RESULT"."TRANSECT_1" IS '枫新河区间水位'
 
   COMMENT ON COLUMN "WRS"."WRS_TRANSECT_RESULT"."TRANSECT_2" IS '河岭区间水位'
 
   COMMENT ON COLUMN "WRS"."WRS_TRANSECT_RESULT"."TRANSECT_3" IS '白岭区间水位'
 
   COMMENT ON COLUMN "WRS"."WRS_TRANSECT_RESULT"."TRANSECT_4" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_TRANSECT_RESULT"."TRANSECT_5" IS '备用字段'
 
   COMMENT ON COLUMN "WRS"."WRS_TRANSECT_RESULT"."CREATE_TIME" IS '创建时间'
 
   COMMENT ON COLUMN "WRS"."WRS_TRANSECT_RESULT"."CREATE_USER_CODE" IS '创建人ID'
 
   COMMENT ON COLUMN "WRS"."WRS_TRANSECT_RESULT"."UPDATE_TIME" IS '修改时间'
 
   COMMENT ON COLUMN "WRS"."WRS_TRANSECT_RESULT"."UPDATE_USER_CODE" IS '修改人ID'
 
   COMMENT ON COLUMN "WRS"."WRS_TRANSECT_RESULT"."IS_DELETE" IS '是否已删除：0-否，1-是'
 
   COMMENT ON COLUMN "WRS"."WRS_TRANSECT_RESULT"."DELETE_TIME" IS '删除时间'
 
   COMMENT ON COLUMN "WRS"."WRS_TRANSECT_RESULT"."DELETE_USER_CODE" IS '删除人ID'
 
   COMMENT ON TABLE "WRS"."WRS_TRANSECT_RESULT"  IS '断面预测成果表';
