TRIGGER APP_DICTIONARY_DATA_TRIGGER BEFORE INSERT ON APP_DICTIONARY_DATA FOR EACH ROW WHEN(NEW.DICT_DATA_ID IS NULL)
BEGIN
SELECT APP_DICTIONARY_DATA_SEQ.NEXTVAL INTO :NEW.DICT_DATA_ID FROM DUAL;
END;

TRIGGER APP_DICTIONARY_TRIGGER BEFORE INSERT ON APP_DICTIONARY FOR EACH ROW WHEN(NEW.DICT_CODE IS NULL)
BEGIN
SELECT APP_DICTIONARY_SEQ.NEXTVAL INTO :NEW.DICT_CODE FROM DUAL;
END;

TRIGGER APP_DOC_CATALOG_TRIGGER BEFORE INSERT ON APP_DOC_CATALOG FOR EACH ROW WHEN(NEW.CATALOG_ID IS NULL)
BEGIN
SELECT APP_DOC_CATALOG_SEQ.NEXTVAL INTO :NEW.CATALOG_ID FROM DUAL;
END;

TRIGGER APP_DOC_TYPE_TRIGGER BEFORE INSERT ON APP_DOC_TYPE FOR EACH ROW WHEN(NEW.TYPE_ID IS NULL)
BEGIN
SELECT APP_DOC_TYPE_SEQ.NEXTVAL INTO :NEW.TYPE_ID FROM DUAL;
END;
